### ISSUE TITLE
when I use the property like this "implicitUtilities: 'utils/*.css'", it comes an error

### ISSUE THREAD

**Issue by Jewl** [simonsmith/stylelint-selector-bem-pattern#34]
when I try to set the property “implicitUtilties“, I got an error like this
![image](https://user-images.githubusercontent.com/17569124/37906015-6149e26a-3133-11e8-9c2c-52521fa99f2c.png)
so I add the statements in your plugin, and it works well
````
implicitUtilities: [_.isBoolean, _.isString, function(pattern) {
    return _.isArray(pattern) && _.every(pattern, _.isString);
  }],
````
Is there anything wrong about the plugin?

**Comment by machal** [comment]
The same here.

My `.stylelintrc`:

```
    "plugin/selector-bem-pattern": {
      "implicitUtilities": "assets/scss/helpers/*.scss",
    }
```

```
$ npm list stylelint
…
├── stylelint@8.4.0 
└─┬ stylelint-selector-bem-pattern@2.0.0
```
