### ISSUE TITLE
Selector should be written in lowercase with hyphens (selector-class-pattern)

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [simonsmith/stylelint-selector-bem-pattern#36]
Hi there!

This plugin was connected successfully, but the BEM rule does not work - the text editor continues to swear at the BEM stylistics. I'm using native VSCode [stylelint](https://github.com/shinnn/vscode-stylelint) plugin for linting styles

**.stylelintrc.yml**

![img-2018-09-24-17-07-56](https://user-images.githubusercontent.com/10127643/45956979-98349400-c01c-11e8-8595-a3522184961d.png)

**VSCode text editor marked problems**
![img-2018-09-24-16-54-26](https://user-images.githubusercontent.com/10127643/45956971-8fdc5900-c01c-11e8-8016-7a0eeb4d6b52.png)

**marked problem in styles**

![img-2018-09-24-17-04-32](https://user-images.githubusercontent.com/10127643/45956774-13497a80-c01c-11e8-999b-84864e500f9b.png)

Any ideas how to solve it?

**Comment by jeddy3** [comment]
Somewhere in your [stylelint configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object) you're turning on the built-in `selector-class-pattern` rule. You probably don't want to use that rule if you're using this plugin.

You can turn off that rule with:

```yaml
rules:
  selector-class-pattern: null
```

**Comment by Andrew-Dyachenko** [comment]
Yes, that is right!
I connected this rule `selector-class-pattern: null` and the error went away.

![img-2018-09-24-17-20-43](https://user-images.githubusercontent.com/10127643/45957851-adaabd80-c01e-11e8-9e60-45a481277180.png)

Now no errors in VSCode

![img-2018-09-24-17-25-56](https://user-images.githubusercontent.com/10127643/45957977-eea2d200-c01e-11e8-9223-867cd93c7174.png)

I expect that this rule was included by extending via `extends: stylelint-config-sass-guidelines` by default...

**Comment by dalberola** [comment]
There is an alternative to disable the rule : 

`"selector-class-pattern": [
      "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",
      {
        "message": "Class names should match the SUIT CSS naming convention"
      }
    ],`

ref : https://github.com/btd1337/stylelint-config-sass-guidelines/blob/master/.stylelintrc
