### ISSUE TITLE
Update to support stylelint@16

### ISSUE THREAD

**Issue by bmuenzenmeyer** [simonsmith/stylelint-selector-bem-pattern#67]
https://github.com/simonsmith/stylelint-selector-bem-pattern/blob/562b9a8e731adab852d9f7b08481ffe15c732ac7/package.json#L36 is holding back stylelint 16 packages.

additionally, shouldn't this be a peerDependency?

**Comment by simonsmith** [comment]
Yeah, it should move to peer
